### ISSUE TITLE
Image View Panel does not show camera image on HoloLens

### ISSUE THREAD

**Issue by franzabist** [abist-co-ltd/hololens-opencv-laserpointer#2]
The scene includes a ImageView panel. When enabling its  isVisibleImage property in the Inspector,
it shows the real time camera image for debugging purposes.
This currently only works in the Unity editor. 

When running on HoloLens, the panel remains gray, does not show the camera image and does not adjust its position to the user position.

**Comment by s-sumi1103** [comment]
テクスチャ画像描画の初期化処理がUnityEditorを実行したときにのみ行われていたため、
HoloLensでの実行処理ルードでも行う場所に処理を移動した
